#!/bin/bash
#SBATCH --workdir /home/tulyakov/research/mil-mc-cnn
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 16384
#SBATCH --time 24:00:00
#SBATCH --qos=gpu
#SBATCH --gres gpu:1
#SBATCH --partition=gpu
echo TRAIN CONTRAST_DPROG STARTING AT `date`
source /etc/profile.d/slmodules.sh -r deprecated
module purge
module load cuda/7.0
module load torch/7
module load opencv/3.0.0-rc1/gcc-4.4.7
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET_MB.lua nodebug -debug_fname 'contrast-dprog-mb' -debug_start_from_fnet 'work/contrast-dprog-mb/fnet_2016_11_02_19:05:06_contrast-dprog-mb.t7'  -debug_start_from_optim 'work/contrast-dprog-mb/optim_2016_11_02_19:05:06_contrast-dprog-mb.t7'
echo FINISHED at `date`
