#!/bin/bash
#SBATCH --workdir /home/tulyakov/research/mil-mc-cnn
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 16384
#SBATCH --time 12:00:00
#SBATCH --qos=gpu_free
#SBATCH --gres gpu:1
#SBATCH --partition=gpu
echo TRAIN MIL_MAX STARTING AT `date`
source /etc/profile.d/slmodules.sh -r deprecated
module purge
module load cuda/7.0
module load torch/7
module load opencv/3.0.0-rc1/gcc-4.4.7
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua mil-max -debug_fname 'mil-max' 
echo FINISHED at `date`
