#!/bin/bash
#SBATCH --workdir /home/tulyakov/research/mil-mc-cnn
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 16384
#SBATCH --time 12:00:00
#SBATCH --qos=gpu_free
#SBATCH --gres gpu:1
#SBATCH --partition=gpu
echo TRAIN MIL_DPROG STARTING AT `date`
source /etc/profile.d/slmodules.sh -r deprecated
module purge
module load cuda/7.0
module load torch/7
module load opencv/2.4.9/gcc-4.4.7
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua mil-dprog -debug_fname "mil-dprog" -debug_start_from_fnet "work/mil-dprog/fnet_2016_10_11_01:17:42_mil-dprog.t7" -debug_start_from_optim "work/mil-dprog/optim_2016_10_11_01:17:42_mil-dprog.t7" 
echo FINISHED at `date`