#!/bin/bash
#SBATCH --workdir /home/tulyakov/research/mil-mc-cnn
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 16384
#SBATCH --time 12:00:00
#SBATCH --qos=gpu
#SBATCH --gres gpu:1
#SBATCH --partition=gpu
echo EXPERIMENT FOR SELECTING OPTIMAL MAX SUPRESSION THRESHOLD AT `date`
source /etc/profile.d/slmodules.sh -r deprecated
module purge
module load cuda/7.0
module load torch/7
module load opencv/3.0.0-rc1/gcc-4.4.7
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua debug contrast-dprog kitti -occ_th 1 -debug_fname 'contrast-dprog-occ1'
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua debug contrast-dprog kitti -occ_th 2 -debug_fname 'contrast-dprog-occ2'
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua debug contrast-dprog kitti -occ_th 4 -debug_fname 'contrast-dprog-occ4'
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua debug contrast-dprog kitti -occ_th 8 -debug_fname 'contrast-dprog-occ8'
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua debug contrast-dprog kitti -occ_th 16 -debug_fname 'contrast-dprog-occ16'
echo FINISHED at `date`

