#!/bin/bash
#SBATCH --workdir /home/tulyakov/research/mil-mc-cnn
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 16384
#SBATCH --time 24:00:00
#SBATCH --qos=gpu
#SBATCH --gres gpu:1
#SBATCH --partition=gpu
echo TRAIN CONTRAST_DPROG FOR KITTI EXTENDED STARTING AT `date`
source /etc/profile.d/slmodules.sh -r deprecated
module purge
module load cuda/7.0
module load torch/7
module load opencv/3.0.0-rc1/gcc-4.4.7
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua contrast-dprog kitti_ext -debug_fname 'contrast-dprog-kitti-ext' -debug_start_from_fnet 'work/contrast-dprog-kitti-ext/fnet_2016_11_13_13:52:36_contrast-dprog-kitti-ext.t7'  -debug_start_from_optim 'work/contrast-dprog-kitti-ext/optim_2016_11_13_13:52:36_contrast-dprog-kitti-ext.t7'
echo FINISHED at `date`
