#!/bin/bash
#SBATCH --workdir /home/tulyakov/research/mil-mc-cnn
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 16384
#SBATCH --time 24:00:00
#SBATCH --qos=gpu
#SBATCH --gres gpu:1
#SBATCH --partition=gpu
echo TRAIN CONTRAST_DPROG STARTING AT `date`
source /etc/profile.d/slmodules.sh -r deprecated
module purge
module load cuda/7.0
module load torch/7
module load opencv/3.0.0-rc1/gcc-4.4.7
th /home/tulyakov/research/mil-mc-cnn/TRAIN_NET.lua contrast-dprog kitti15_ext -debug_fname 'contrast-dprog-kitti15-ext' -debug_start_from_fnet ''  -debug_start_from_optim ''
echo FINISHED at `date`
