#!/bin/bash
#SBATCH --workdir /home/tulyakov/research/mc-cnn
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 2
#SBATCH --mem 60000
#SBATCH --time 24:00:00
#SBATCH --qos gpu
#SBATCH --gres gpu:1
#SBATCH --partition=gpu
echo STARTING AT `date`
echo "TUNINIG DAISY"
module purge
module load cuda/7.0
module load torch/7
module load opencv/2.4.9/gcc-4.4.7
luajit /home/tulyakov/research/mc-cnn/tune_stereo_hyperparams.lua 'mb daisy -a test_te'
echo FINISHED at `date`
